package com.nextgate.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-19T16:41:10.571+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://nextgate.com/nextgate-service", name = "ExecuteMatchUpdatePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ExecuteMatchUpdatePort {

    @WebMethod
    @WebResult(name = "getExecuteMatchUpdateResponse", targetNamespace = "http://nextgate.com/nextgate-service", partName = "getExecuteMatchUpdateResponse")
    public GetExecuteMatchUpdateResponse getExecuteMatchUpdate(
        @WebParam(partName = "getExecuteMatchUpdateRequest", name = "getExecuteMatchUpdateRequest", targetNamespace = "http://nextgate.com/nextgate-service")
        GetExecuteMatchUpdateRequest getExecuteMatchUpdateRequest
    );
}
