package com.nextgate.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-19T16:41:10.598+08:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "ExecuteMatchUpdatePortService",
                  wsdlLocation = "http://healthcare-nextgate.apps.example.com/services/executeMatchUpdate.wsdl",
                  targetNamespace = "http://nextgate.com/nextgate-service")
public class ExecuteMatchUpdatePortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://nextgate.com/nextgate-service", "ExecuteMatchUpdatePortService");
    public final static QName ExecuteMatchUpdatePortSoap11 = new QName("http://nextgate.com/nextgate-service", "ExecuteMatchUpdatePortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://healthcare-nextgate.apps.example.com/services/executeMatchUpdate.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExecuteMatchUpdatePortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://healthcare-nextgate.apps.example.com/services/executeMatchUpdate.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExecuteMatchUpdatePortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExecuteMatchUpdatePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecuteMatchUpdatePortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ExecuteMatchUpdatePortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExecuteMatchUpdatePortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExecuteMatchUpdatePortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ExecuteMatchUpdatePort
     */
    @WebEndpoint(name = "ExecuteMatchUpdatePortSoap11")
    public ExecuteMatchUpdatePort getExecuteMatchUpdatePortSoap11() {
        return super.getPort(ExecuteMatchUpdatePortSoap11, ExecuteMatchUpdatePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecuteMatchUpdatePort
     */
    @WebEndpoint(name = "ExecuteMatchUpdatePortSoap11")
    public ExecuteMatchUpdatePort getExecuteMatchUpdatePortSoap11(WebServiceFeature... features) {
        return super.getPort(ExecuteMatchUpdatePortSoap11, ExecuteMatchUpdatePort.class, features);
    }

}
